<testsuite name="features.division.Perform an division Feature" tests="4" errors="4" failures="0" skipped="0" time="0.029979" timestamp="2023-05-30T13:50:13.406968" hostname="DESKTOP-K37OCDU"><testcase classname="features.division.Perform an division Feature" name="Divide the Two number -- @1.1 " status="failed" time="0.00899"><error type="AttributeError" message="'Context' object has no attribute 'first_number'">
<![CDATA[
Failing step: And if both are same, return 0 ... failed in 0.006s
Location: features/division.feature:10
Traceback (most recent call last):
  File "C:\Users\Jatin-PC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\Jatin-PC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\steps.py", line 50, in step_impl
    if int(context.first_number) == int(context.second_number):
  File "C:\Users\Jatin-PC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\behave\runner.py", line 321, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'first_number'

Captured stdout:
FIRST NUMBER :  4
SECOND NUMBER :  2
Not divide by Zero
RESULT IS :  0]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario Outline: Divide the Two number -- @1.1 
    Given take the "4" and "2" ... passed in 0.001s
    When verify if greater number between "4" and "2" ... passed in 0.001s
    And divide greater with lower ... passed in 0.000s
    Then Print the total result ... passed in 0.001s
    And if both are same, return 0 ... failed in 0.006s

@scenario.end
--------------------------------------------------------------------------------

Captured stdout:
FIRST NUMBER :  4
SECOND NUMBER :  2
Not divide by Zero
RESULT IS :  0

]]>
</system-out></testcase><testcase classname="features.division.Perform an division Feature" name="Divide the Two number -- @1.2 " status="failed" time="0.006996"><error type="AttributeError" message="'Context' object has no attribute 'first_number'">
<![CDATA[
Failing step: And if both are same, return 0 ... failed in 0.003s
Location: features/division.feature:10
Traceback (most recent call last):
  File "C:\Users\Jatin-PC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\Jatin-PC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\steps.py", line 50, in step_impl
    if int(context.first_number) == int(context.second_number):
  File "C:\Users\Jatin-PC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\behave\runner.py", line 321, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'first_number'

Captured stdout:
FIRST NUMBER :  2
SECOND NUMBER :  0
Not divide by Zero
RESULT IS :  0]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario Outline: Divide the Two number -- @1.2 
    Given take the "2" and "0" ... passed in 0.001s
    When verify if greater number between "2" and "0" ... passed in 0.002s
    And divide greater with lower ... passed in 0.001s
    Then Print the total result ... passed in 0.000s
    And if both are same, return 0 ... failed in 0.003s

@scenario.end
--------------------------------------------------------------------------------

Captured stdout:
FIRST NUMBER :  2
SECOND NUMBER :  0
Not divide by Zero
RESULT IS :  0

]]>
</system-out></testcase><testcase classname="features.division.Perform an division Feature" name="Divide the Two number -- @1.3 " status="failed" time="0.006995"><error type="AttributeError" message="'Context' object has no attribute 'first_number'">
<![CDATA[
Failing step: And if both are same, return 0 ... failed in 0.003s
Location: features/division.feature:10
Traceback (most recent call last):
  File "C:\Users\Jatin-PC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\Jatin-PC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\steps.py", line 50, in step_impl
    if int(context.first_number) == int(context.second_number):
  File "C:\Users\Jatin-PC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\behave\runner.py", line 321, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'first_number'

Captured stdout:
FIRST NUMBER :  -2
SECOND NUMBER :  0
Not divide by Zero
RESULT IS :  0]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario Outline: Divide the Two number -- @1.3 
    Given take the "-2" and "0" ... passed in 0.001s
    When verify if greater number between "-2" and "0" ... passed in 0.001s
    And divide greater with lower ... passed in 0.001s
    Then Print the total result ... passed in 0.001s
    And if both are same, return 0 ... failed in 0.003s

@scenario.end
--------------------------------------------------------------------------------

Captured stdout:
FIRST NUMBER :  -2
SECOND NUMBER :  0
Not divide by Zero
RESULT IS :  0

]]>
</system-out></testcase><testcase classname="features.division.Perform an division Feature" name="Divide the Two number -- @1.4 " status="failed" time="0.006997"><error type="AttributeError" message="'Context' object has no attribute 'first_number'">
<![CDATA[
Failing step: And if both are same, return 0 ... failed in 0.002s
Location: features/division.feature:10
Traceback (most recent call last):
  File "C:\Users\Jatin-PC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\Jatin-PC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\steps.py", line 50, in step_impl
    if int(context.first_number) == int(context.second_number):
  File "C:\Users\Jatin-PC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\behave\runner.py", line 321, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'first_number'

Captured stdout:
FIRST NUMBER :  -2
SECOND NUMBER :  -2
Not divide by Zero
RESULT IS :  0]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario Outline: Divide the Two number -- @1.4 
    Given take the "-2" and "-2" ... passed in 0.001s
    When verify if greater number between "-2" and "-2" ... passed in 0.001s
    And divide greater with lower ... passed in 0.001s
    Then Print the total result ... passed in 0.002s
    And if both are same, return 0 ... failed in 0.002s

@scenario.end
--------------------------------------------------------------------------------

Captured stdout:
FIRST NUMBER :  -2
SECOND NUMBER :  -2
Not divide by Zero
RESULT IS :  0

]]>
</system-out></testcase></testsuite>